#https://www.ory.sh/docs/kratos/reference/configuration
version: v1.3.1

serve:
  public:
    base_url: http://localhost:4433
    cors:
      enabled: false

  admin:
    base_url: http://localhost:4434

session:
  whoami:
    required_aal: aal1

selfservice:
  default_browser_return_url: http://localhost:3000
  allowed_return_urls:
    - http://localhost:3000
  methods:
    profile:
      enabled: false
    password:
      enabled: true
    lookup_secret:
      enabled: true
    totp:
      config:
        issuer: OryTotp.com
      enabled: true
    code:
      passwordless_enabled: true
      mfa_enabled: false
      enabled: true
      config:
        lifespan: 15m
        missing_credential_fallback_enabled: true
    webauthn:
      enabled: true
      config:
        passwordless: true
        rp:
          display_name: Ory WebAuthn
          id: localhost
          origins:
            - http://localhost:3000
    passkey:
      enabled: true
      config:
        rp:
          passwordless: true
          display_name: Ory Passkey
          id: localhost
          origins:
            - http://localhost:3000

  flows:
    error:
      ui_url: http://localhost:3000/error
    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m
      required_aal: aal1
    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
      use: code
      notify_unknown_recipients: false
      after:
        hooks:
          - hook: revoke_active_sessions
    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      lifespan: 10m
      use: code
    login:
      ui_url: http://localhost:3000/auth/login
      lifespan: 10m
      style: identifier_first
    registration:
      enable_legacy_one_step: false
      lifespan: 10m
      ui_url: http://localhost:3000/auth/registration
      after:
        oidc:
          hooks:
            - hook: session
        code:
          hooks:
            - hook: session
        passkey:
          hooks:
            - hook: session
            - hook: show_verification_ui
        webauthn:
          hooks:
            - hook: session
            - hook: show_verification_ui
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: trace
  format: text
  leak_sensitive_values: true

secrets:
  default:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cookie:
    - CHANGE_ME_TO_REAL_SECRET
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  delivery_strategy: http
  http:
    request_config:
      url: http://host.docker.internal:3001/kratos/email
      method: POST
      headers:
        Content-Type: 'application/json'
      body: file:///etc/config/kratos/mail.template.jsonnet
      # auth:
      #   type: api_key
      #   config:
      #     name: Authorization
      #     value: Bearer <API_KEY>
      #     in: header
oauth2_provider:
  url: http://hydra:4445
